#!/usr/bin/env bash
# Deploy provider credentials to Node B for the go-choir-gateway service.
#
# This script reads API keys from ~/.factory/settings.json (customModels entries)
# and writes them to /var/lib/go-choir/gateway-provider.env on Node B via SSH.
# The gateway systemd service loads this file via EnvironmentFile.
#
# IMPORTANT: This script never commits credentials to the repo or Nix store.
# The EnvironmentFile is a writable runtime location on Node B only.
#
# Usage:
#   ./nix/deploy-provider-creds.sh           # deploy to node-b (default)
#   ./nix/deploy-provider-creds.sh node-b    # explicit host
#
# Required: jq, ssh access to Node B
set -euo pipefail

HOST="${1:-node-b}"
SETTINGS="${HOME}/.factory/settings.json"
REMOTE_ENV_FILE="/var/lib/go-choir/gateway-provider.env"

if [ ! -f "$SETTINGS" ]; then
  echo "error: $SETTINGS not found" >&2
  exit 1
fi

# Build the env file content from customModels entries.
# We detect the provider type by apiKey prefix and baseUrl.
ENVS=()

# Extract all customModels entries with their provider info
NUM_MODELS=$(jq '.customModels | length' "$SETTINGS")

for i in $(seq 0 $((NUM_MODELS - 1))); do
  API_KEY=$(jq -r ".customModels[$i].apiKey" "$SETTINGS")
  BASE_URL=$(jq -r ".customModels[$i].baseUrl // empty" "$SETTINGS")
  PROVIDER=$(jq -r ".customModels[$i].provider // empty" "$SETTINGS")
  MODEL=$(jq -r ".customModels[$i].model // empty" "$SETTINGS")

  if [ -z "$API_KEY" ]; then
    continue
  fi

  # Detect Z.AI keys (baseUrl contains z.ai)
  if echo "$BASE_URL" | grep -q "z\.ai"; then
    if ! printf '%s\n' "${ENVS[@]}" | grep -q "^ZAI_API_KEY="; then
      ENVS+=("ZAI_API_KEY=${API_KEY}")
      [ -n "$MODEL" ] && ENVS+=("RUNTIME_ZAI_MODEL=${MODEL}")
    fi
    continue
  fi

  # Detect Fireworks keys (apiKey starts with fw_ or baseUrl contains fireworks)
  if echo "$API_KEY" | grep -q "^fw_" || echo "$BASE_URL" | grep -q "fireworks"; then
    if ! printf '%s\n' "${ENVS[@]}" | grep -q "^FIREWORKS_API_KEY="; then
      ENVS+=("FIREWORKS_API_KEY=${API_KEY}")
      [ -n "$MODEL" ] && ENVS+=("RUNTIME_FIREWORKS_MODEL=${MODEL}")
      [ -n "$BASE_URL" ] && ENVS+=("FIREWORKS_BASE_URL=${BASE_URL}")
    fi
    continue
  fi

  # Detect Bedrock keys (baseUrl contains bedrock or provider mentions bedrock)
  if echo "$BASE_URL" | grep -q "bedrock" || echo "$PROVIDER" | grep -qi "bedrock"; then
    if ! printf '%s\n' "${ENVS[@]}" | grep -q "^AWS_BEARER_TOKEN_BEDROCK="; then
      ENVS+=("AWS_BEARER_TOKEN_BEDROCK=${API_KEY}")
      [ -n "$MODEL" ] && ENVS+=("RUNTIME_BEDROCK_MODEL=${MODEL}")
    fi
    continue
  fi
done

if [ ${#ENVS[@]} -eq 0 ]; then
  echo "warning: no provider credentials found in $SETTINGS" >&2
  exit 0
fi

# Build the env file content
ENV_CONTENT=$(printf '%s\n' "${ENVS[@]}")
ENV_CONTENT="${ENV_CONTENT}
# Auto-generated by deploy-provider-creds.sh — DO NOT COMMIT
# Regenerate with: ./nix/deploy-provider-creds.sh"

echo "Deploying ${#ENVS[@]} credential entries to ${HOST}:${REMOTE_ENV_FILE}"

# Write the env file on Node B and restart the gateway service.
# Use a temp file and atomic move to avoid partial writes.
ssh "$HOST" "cat > ${REMOTE_ENV_FILE}.tmp << 'PROVIDER_ENV_EOF'
${ENV_CONTENT}
PROVIDER_ENV_EOF
mv ${REMOTE_ENV_FILE}.tmp ${REMOTE_ENV_FILE}
chmod 600 ${REMOTE_ENV_FILE}
systemctl restart go-choir-gateway
echo 'Provider credentials deployed and gateway restarted.'
systemctl is-active go-choir-gateway"

echo "Done."
